; ePitaka Windows installer script (NSIS 3.x)
; Build with: makensis.exe install\windows\epitaka.nsi
; Icon generated by flutter_launcher_icons at windows\runner\resources\app_icon.ico

!include "MUI2.nsh"

; Solid LZMA keeps the installer small (bundled DBs are ~700MB)
SetCompressor /SOLID lzma

Name "ePitaka"
OutFile "epitaka-windows-x64-setup.exe"
InstallDir "$PROGRAMFILES64\ePitaka"
RequestExecutionLevel admin

!define MUI_ICON "..\..\windows\runner\resources\app_icon.ico"
!define MUI_UNICON "..\..\windows\runner\resources\app_icon.ico"
!define MUI_ABORTWARNING

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "$INSTDIR"
  File /r "..\..\build\windows\x64\runner\Release\*.*"

  ; Start menu + desktop shortcuts
  CreateDirectory "$SMPROGRAMS\ePitaka"
  CreateShortcut "$SMPROGRAMS\ePitaka\ePitaka.lnk" "$INSTDIR\epitaka.exe"
  CreateShortcut "$DESKTOP\ePitaka.lnk" "$INSTDIR\epitaka.exe"

  ; Uninstaller + registry entry
  WriteUninstaller "$INSTDIR\uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\ePitaka" "DisplayName" "ePitaka"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\ePitaka" "DisplayVersion" "${VERSION}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\ePitaka" "Publisher" "Dhammanana"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\ePitaka" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\ePitaka" "DisplayIcon" "$INSTDIR\epitaka.exe"
SectionEnd

Section "Uninstall"
  Delete "$INSTDIR\uninstall.exe"
  RMDir /r "$INSTDIR"
  Delete "$SMPROGRAMS\ePitaka\ePitaka.lnk"
  RMDir "$SMPROGRAMS\ePitaka"
  Delete "$DESKTOP\ePitaka.lnk"
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\ePitaka"
SectionEnd
